// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.Database;

#nullable disable

namespace Shared.Migrations
{
    [DbContext(typeof(FFXIIIDbContext))]
    [Migration("20241227104215_Avatar")]
    partial class Avatar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Database.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BaseEXP")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyPrice")
                        .HasColumnType("bigint");

                    b.Property<bool>("Buyable")
                        .HasColumnType("bit");

                    b.Property<int>("Catalysator")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<long>("IncreaseEXP")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NexusGroup")
                        .HasColumnType("int");

                    b.Property<long>("Rank")
                        .HasColumnType("bigint");

                    b.Property<long>("SellPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("SpecialEffect")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasDiscriminator().HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shared.Database.Models.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BearerToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExpirationDateBearerToken")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpirationDateResetToken")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResetToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Shared.Database.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Base64AvatarImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shared.Database.Models.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Role = "Administrator"
                        },
                        new
                        {
                            Id = 2L,
                            Role = "User"
                        });
                });

            modelBuilder.Entity("Shared.Database.Models.Accessoire", b =>
                {
                    b.HasBaseType("Shared.Database.Models.Item");

                    b.Property<long?>("MaxValue")
                        .HasColumnType("bigint");

                    b.Property<long?>("MinValue")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpgradeToAccessoireId")
                        .HasColumnType("bigint");

                    b.HasIndex("UpgradeToAccessoireId");

                    b.HasDiscriminator().HasValue("Accessoire");
                });

            modelBuilder.Entity("Shared.Database.Models.Weapon", b =>
                {
                    b.HasBaseType("Shared.Database.Models.Item");

                    b.Property<long>("MaxMagicDamage")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxPhysicalDamage")
                        .HasColumnType("bigint");

                    b.Property<long>("MinMagicDamage")
                        .HasColumnType("bigint");

                    b.Property<long>("MinPhysicalDamage")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpgradeToWeaponId")
                        .HasColumnType("bigint");

                    b.HasIndex("UpgradeToWeaponId");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("Shared.Database.Models.Session", b =>
                {
                    b.HasOne("Shared.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Database.Models.User", b =>
                {
                    b.HasOne("Shared.Database.Models.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Shared.Database.Models.Accessoire", b =>
                {
                    b.HasOne("Shared.Database.Models.Accessoire", "UpgradeToAccessoire")
                        .WithMany()
                        .HasForeignKey("UpgradeToAccessoireId");

                    b.Navigation("UpgradeToAccessoire");
                });

            modelBuilder.Entity("Shared.Database.Models.Weapon", b =>
                {
                    b.HasOne("Shared.Database.Models.Weapon", "UpgradeToWeapon")
                        .WithMany()
                        .HasForeignKey("UpgradeToWeaponId");

                    b.Navigation("UpgradeToWeapon");
                });
#pragma warning restore 612, 618
        }
    }
}
