// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestAPI.Database;

#nullable disable

namespace RestAPI.Migrations
{
    [DbContext(typeof(FFXIIIDbContext))]
    [Migration("20241216003136_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestAPI.Database.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BaseEXP")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyPrice")
                        .HasColumnType("bigint");

                    b.Property<bool>("Buyable")
                        .HasColumnType("bit");

                    b.Property<int>("Catalysator")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<long>("IncreaseEXP")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NexusGroup")
                        .HasColumnType("int");

                    b.Property<long>("Rank")
                        .HasColumnType("bigint");

                    b.Property<long>("SellPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("SpecialEffect")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Item");

                    b.HasDiscriminator().HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RestAPI.Database.Models.Accessoire", b =>
                {
                    b.HasBaseType("RestAPI.Database.Models.Item");

                    b.Property<long?>("MaxValue")
                        .HasColumnType("bigint");

                    b.Property<long?>("MinValue")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpgradeToAccessoireId")
                        .HasColumnType("bigint");

                    b.HasIndex("UpgradeToAccessoireId");

                    b.HasDiscriminator().HasValue("Accessoire");
                });

            modelBuilder.Entity("RestAPI.Database.Models.Weapon", b =>
                {
                    b.HasBaseType("RestAPI.Database.Models.Item");

                    b.Property<long>("MaxMagicDamage")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxPhysicalDamage")
                        .HasColumnType("bigint");

                    b.Property<long>("MinMagicDamage")
                        .HasColumnType("bigint");

                    b.Property<long>("MinPhysicalDamage")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpgradeToWeaponId")
                        .HasColumnType("bigint");

                    b.HasIndex("UpgradeToWeaponId");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("RestAPI.Database.Models.Accessoire", b =>
                {
                    b.HasOne("RestAPI.Database.Models.Accessoire", "UpgradeToAccessoire")
                        .WithMany()
                        .HasForeignKey("UpgradeToAccessoireId");

                    b.Navigation("UpgradeToAccessoire");
                });

            modelBuilder.Entity("RestAPI.Database.Models.Weapon", b =>
                {
                    b.HasOne("RestAPI.Database.Models.Weapon", "UpgradeToWeapon")
                        .WithMany()
                        .HasForeignKey("UpgradeToWeaponId");

                    b.Navigation("UpgradeToWeapon");
                });
#pragma warning restore 612, 618
        }
    }
}
